services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:5000"
    volumes:
      - ./backend:/app
      - model-data:/app/models
    environment:
      - MODEL_PATH=/app/models
    networks:
      - app-network

volumes:
  model-data:
    driver: local

networks:
  app-network:
    driver: bridge 